import type { DatabaseSync } from 'node:sqlite';
import { now } from './db.js';

export type AttentionItem={source_type:string;source_id:number;approval_id?:number|undefined;category:string;required_action:string;deadline?:string|undefined;revenue_impact_cents:number;risk:string;context:string;priority:number};

export function founderAttention(db:DatabaseSync,limit=50):AttentionItem[]{
  const items:AttentionItem[]=[];
  const approvals=db.prepare("SELECT a.*,COALESCE(l.estimated_deal_cents,p.quoted_revenue_cents,0) revenue FROM approvals a LEFT JOIN communications c ON a.subject_type='COMMUNICATION' AND c.id=a.subject_id LEFT JOIN leads l ON l.id=c.lead_id LEFT JOIN projects p ON a.subject_type='PROJECT' AND p.id=a.subject_id WHERE a.status='PENDING'").all() as Record<string,unknown>[];
  for(const row of approvals)items.push({source_type:'APPROVAL',source_id:Number(row.id),approval_id:Number(row.id),category:'DECISION',required_action:String(row.action_summary),deadline:row.expires_at?String(row.expires_at):undefined,revenue_impact_cents:Number(row.revenue||0),risk:String(row.risks_json||'[]'),context:String(row.recommendation||''),priority:1});
  const leads=db.prepare("SELECT * FROM leads WHERE stage IN ('REPLIED','DISCOVERY','PROPOSAL_SENT','NEGOTIATION')").all() as Record<string,unknown>[];
  for(const row of leads)items.push({source_type:'LEAD',source_id:Number(row.id),category:'SALES',required_action:`Review ${row.company} conversation`,deadline:row.next_action_at?String(row.next_action_at):undefined,revenue_impact_cents:Number(row.estimated_deal_cents||0),risk:'A warm prospect may cool without a decision.',context:`Stage ${row.stage}. ${row.next_action||'Choose the next approved response.'}`,priority:2});
  const agreements=db.prepare("SELECT a.*,p.title,p.quoted_revenue_cents FROM agreements a JOIN projects p ON p.id=a.project_id WHERE a.signature_status!='ACCEPTED' AND p.status!='ARCHIVED'").all() as Record<string,unknown>[];
  for(const row of agreements)items.push({source_type:'AGREEMENT',source_id:Number(row.id),category:'CONTRACT',required_action:`Resolve agreement for ${row.title}`,revenue_impact_cents:Number(row.quoted_revenue_cents||0),risk:'Production cannot begin without accepted terms.',context:`Signature state: ${row.signature_status}.`,priority:2});
  const invoices=db.prepare("SELECT i.*,p.title,p.quoted_revenue_cents FROM invoices i JOIN projects p ON p.id=i.project_id WHERE i.status NOT IN ('PAID','VOID','REFUNDED') AND p.status!='ARCHIVED'").all() as Record<string,unknown>[];
  for(const row of invoices)items.push({source_type:'INVOICE',source_id:Number(row.id),category:'PAYMENT',required_action:`Resolve ${row.invoice_number} for ${row.title}`,deadline:row.due_at?String(row.due_at):undefined,revenue_impact_cents:Number(row.amount_cents||0),risk:'Production or final delivery may remain blocked.',context:`Invoice state: ${row.status}. Manual payment confirmation only.`,priority:1});
  const production=db.prepare("SELECT pi.*,p.title project_title,p.quoted_revenue_cents FROM production_items pi JOIN projects p ON p.id=pi.project_id WHERE pi.stage IN ('ASSETS_NEEDED','BLOCKED','APPROVED') AND p.status!='ARCHIVED'").all() as Record<string,unknown>[];
  for(const row of production){const assets=row.stage==='ASSETS_NEEDED';items.push({source_type:'PRODUCTION_ITEM',source_id:Number(row.id),category:assets?'FOOTAGE':'DELIVERY',required_action:assets?`Record or supply footage for ${row.title}`:`Resolve ${row.stage==='APPROVED'?'final delivery':'client emergency'} for ${row.title}`,deadline:row.deadline?String(row.deadline):undefined,revenue_impact_cents:Number(row.quoted_revenue_cents||0),risk:String(row.blocked_reason||'Client deadline or delivery gate requires attention.'),context:`${row.project_title} · stage ${row.stage}`,priority:assets?2:1});}
  const queue=db.prepare("SELECT * FROM work_queue WHERE status IN ('WAITING_APPROVAL','BLOCKED','FAILED') OR (status IN ('READY','CLAIMED') AND priority_class<=3)").all() as Record<string,unknown>[];
  for(const row of queue){if(row.required_approval_id&&approvals.some(a=>Number(a.id)===Number(row.required_approval_id)))continue;items.push({source_type:'WORK_QUEUE',source_id:Number(row.id),approval_id:row.required_approval_id?Number(row.required_approval_id):undefined,category:'OPERATIONS',required_action:String(row.title),deadline:row.deadline?String(row.deadline):undefined,revenue_impact_cents:Number(row.business_value_cents||0),risk:String(row.status)==='FAILED'?'A required operation failed.':'A paid deadline or safety gate needs a decision.',context:String(row.next_action||row.completion_criteria||''),priority:Number(row.priority_class||3)});}
  const activeDeferrals=new Set((db.prepare('SELECT source_type,source_id FROM attention_deferrals WHERE deferred_until>?').all(now()) as {source_type:string;source_id:number}[]).map(row=>`${row.source_type}:${row.source_id}`));
  return items.filter(item=>!activeDeferrals.has(`${item.source_type}:${item.source_id}`)).sort((a,b)=>a.priority-b.priority||String(a.deadline||'9999').localeCompare(String(b.deadline||'9999'))||b.revenue_impact_cents-a.revenue_impact_cents).slice(0,limit);
}

export function deferAttention(db:DatabaseSync,sourceType:string,sourceId:number,reason=''):void{
  const allowed=['APPROVAL','LEAD','AGREEMENT','INVOICE','PRODUCTION_ITEM','WORK_QUEUE'];if(!allowed.includes(sourceType)||!Number.isInteger(sourceId)||sourceId<1)throw new Error('Invalid attention item.');const until=new Date(Date.now()+24*60*60*1000).toISOString();db.prepare(`INSERT INTO attention_deferrals(source_type,source_id,deferred_until,deferred_by,reason,created_at) VALUES(?,?,?,'CHRIS',?,?) ON CONFLICT(source_type,source_id) DO UPDATE SET deferred_until=excluded.deferred_until,deferred_by=excluded.deferred_by,reason=excluded.reason,created_at=excluded.created_at`).run(sourceType,sourceId,until,reason||null,now());db.prepare("INSERT INTO audit_events(actor_type,actor_id,event_type,subject_type,subject_id,summary,detail_json,created_at) VALUES('HUMAN','CHRIS','ATTENTION_DEFERRED',?,?,?,'{}',?)").run(sourceType,sourceId,`Attention item deferred until ${until}.`,now());
}
