import type { DatabaseSync } from 'node:sqlite';
import { setting } from './db.js';

const esc=(value:unknown)=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]!));
const rows=(items:Record<string,unknown>[],render:(row:Record<string,unknown>)=>string,empty='No data yet.')=>items.length?items.map(render).join(''):`<div class="empty">${empty}</div>`;
export function dashboard(db:DatabaseSync):string {
  const mode=setting(db,'publishing_mode','MANUAL_APPROVAL'), lifecycle=setting(db,'lifecycle','COLD_START'), stopped=setting(db,'emergency_stop',false);
  const candidates=db.prepare(`SELECT c.*,ci.concept,ci.product_id,p.name product_name FROM creative_candidates c JOIN content_ideas ci ON ci.id=c.content_idea_id JOIN products p ON p.id=ci.product_id ORDER BY c.id DESC LIMIT 8`).all() as Record<string,unknown>[];
  const products=db.prepare('SELECT * FROM products ORDER BY opportunity_score DESC').all() as Record<string,unknown>[];
  const experiments=db.prepare('SELECT * FROM experiments ORDER BY id DESC').all() as Record<string,unknown>[];
  const posts=db.prepare('SELECT * FROM published_posts ORDER BY published_at DESC LIMIT 10').all() as Record<string,unknown>[];
  const findings=db.prepare('SELECT * FROM agent_findings ORDER BY id DESC LIMIT 8').all() as Record<string,unknown>[];
  const jobs=db.prepare('SELECT * FROM publishing_jobs ORDER BY scheduled_for DESC LIMIT 8').all() as Record<string,unknown>[];
  const activity=db.prepare('SELECT * FROM agent_activity ORDER BY id DESC LIMIT 12').all() as Record<string,unknown>[];
  const programs=db.prepare('SELECT *,CASE WHEN clicks>0 THEN commission/clicks ELSE NULL END epc FROM affiliate_programs ORDER BY commission DESC').all() as Record<string,unknown>[];
  const idea=db.prepare('SELECT ci.*,p.name product_name FROM content_ideas ci JOIN products p ON p.id=ci.product_id ORDER BY ci.id DESC LIMIT 1').get() as Record<string,unknown>|undefined;
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>UGC Command</title><link rel="stylesheet" href="/app.css"></head><body>
  <header><div><span class="eyebrow">ECHOV4ULT // LOCAL CONTROL</span><h1>UGC COMMAND</h1></div><div class="status-dot ${stopped?'danger':'live'}">${stopped?'EMERGENCY STOP':'SYSTEM READY'}</div></header>
  <main><section class="status-grid">
    <article><label>Publishing mode</label><strong>${esc(mode)}</strong><form method="post" action="/actions/mode"><select name="mode">${['OFF','MANUAL_APPROVAL','SCHEDULED','AUTONOMOUS'].map(x=>`<option ${x===mode?'selected':''}>${x}</option>`).join('')}</select><button>Update</button></form></article>
    <article><label>Lifecycle</label><strong>${esc(lifecycle)}</strong><span>Caps are enforced before every transport call.</span></article>
    <article><label>Agents</label><strong>VANTAGE / SCOUT</strong><span>Local services · bounded execution</span></article>
    <article class="stop"><label>Kill switch</label><strong>${stopped?'ACTIVE':'ARMED'}</strong><form method="post" action="/actions/emergency-stop"><input type="hidden" name="active" value="${stopped?'false':'true'}"><button>${stopped?'Resume manually':'EMERGENCY STOP'}</button></form></article>
  </section>
  <section><div class="section-head"><div><span class="eyebrow">NEXT DECISION</span><h2>Today's Mission</h2></div>${idea?`<form method="post" action="/actions/generate"><input type="hidden" name="ideaId" value="${idea.id}"><button>Generate candidate</button></form>`:''}</div>${idea?`<div class="mission"><div><span class="tag">${esc(idea.product_name)}</span><h3>${esc(idea.concept)}</h3><p>${esc(idea.hook)} · ${esc(idea.angle)} · ${esc(idea.format)}</p></div></div>`:'<div class="empty">No data yet.</div>'}
  <div class="section-head lab"><div><span class="eyebrow">CANDIDATE QA</span><h2>Creative Lab</h2></div></div><div class="cards">${rows(candidates,r=>`<article class="candidate"><div><span class="tag">${esc(r.status)}</span><span class="score">${esc(r.score)}/100</span></div><h3>${esc(r.product_name)}</h3><p>${esc(r.concept)}</p><details><summary>Preview and score dimensions</summary><p>${esc(r.script)}</p><p>${esc(r.caption)}</p><pre>${esc(JSON.stringify(JSON.parse(String(r.score_dimensions_json)),null,2))}</pre></details><div class="actions">${r.status==='READY'?`<form method="post" action="/actions/approve"><input type="hidden" name="id" value="${r.id}"><button>Approve</button></form>`:''}<form method="post" action="/actions/reject"><input type="hidden" name="id" value="${r.id}"><button class="secondary">Reject</button></form><form method="post" action="/actions/hold"><input type="hidden" name="id" value="${r.id}"><button class="secondary">Hold</button></form><form method="post" action="/actions/generate"><input type="hidden" name="ideaId" value="${r.content_idea_id}"><button class="secondary">Regenerate</button></form><form method="post" action="/actions/variants"><input type="hidden" name="productId" value="${r.product_id}"><button class="secondary">Variants</button></form>${r.status==='APPROVED'?`<form method="post" action="/actions/publish"><input type="hidden" name="id" value="${r.id}"><button>Publish now</button></form>`:''}</div></article>`)}</div></section>
  <section class="split"><div><span class="eyebrow">SCOUT</span><h2>Product Radar</h2>${rows(products,r=>`<div class="row"><div><strong>${esc(r.name)}</strong><small>${esc(r.evidence_state)}</small><details><summary>17 opportunity dimensions</summary><pre>${esc(JSON.stringify(JSON.parse(String(r.opportunity_dimensions_json)),null,2))}</pre></details></div><b>${esc(r.opportunity_score)}</b></div>`)}</div><div><span class="eyebrow">TEST MATRIX</span><h2>Experiment Board</h2>${rows(experiments,r=>`<div class="row"><div><strong>${esc(r.name)}</strong><small>${esc(r.hypothesis)}</small></div><span>${esc(r.status)}</span></div>`)}</div></section>
  <section class="split"><div><span class="eyebrow">SIGNAL</span><h2>Performance</h2><nav class="tabs">Today · 7d · 30d · Lifetime</nav>${rows(posts,r=>`<div class="row"><div><strong>${esc(r.hook)}</strong><small>${esc(r.published_at)}</small></div><span>${esc(r.experiment_tag)}</span></div>`)}</div><div><span class="eyebrow">PATTERNS</span><h2>Learning Memory</h2>${rows(findings,r=>`<div class="row"><div><strong>${esc(r.finding)}</strong><small>n=${esc(r.sample_size)} · confidence ${esc(r.confidence)}</small><form method="post" action="/actions/finding"><input type="hidden" name="id" value="${r.id}">${['ACCEPT','QUESTION','IGNORE'].map(x=>`<button class="secondary" name="disposition" value="${x}">${x}</button>`).join('')}</form></div><span>${esc(r.disposition)}</span></div>`)}</div></section>
  <section class="split"><div><span class="eyebrow">QUEUE</span><h2>Content Calendar</h2>${rows(jobs,r=>`<div class="row"><div><strong>Job #${esc(r.id)}</strong><small>${esc(r.scheduled_for)}</small></div><span>${esc(r.status)}</span></div>`)}</div><div><span class="eyebrow">AUDIT TRAIL</span><h2>Agent Activity</h2>${rows(activity,r=>`<div class="row"><div><strong>${esc(r.agent)} · ${esc(r.action)}</strong><small>${esc(r.summary)}</small></div><time>${esc(String(r.created_at).slice(11,16))}</time></div>`)}</div></section>
  <section><span class="eyebrow">COMMERCE</span><h2>Money</h2>${rows(programs,r=>`<div class="money"><strong>${esc(r.name)}</strong><span>${esc(r.money_status)}</span><span>Clicks ${esc(r.clicks)}</span><span>Orders ${esc(r.orders)}</span><span>Revenue $${esc(r.revenue)}</span><span>Commission $${esc(r.commission)}</span><span>EPC ${r.epc==null?'unavailable':'$'+esc(r.epc)}</span></div>`)}</section>
  </main><script>document.querySelectorAll('form').forEach(f=>f.addEventListener('submit',()=>{const b=f.querySelector('button');if(b)b.disabled=true}));</script></body></html>`;
}

export const css=`:root{color-scheme:dark;--bg:#070a0c;--panel:#0e1418;--line:#253039;--text:#edf4f2;--muted:#82918c;--green:#53f5a5;--amber:#ffc857;--red:#ff5263;font:15px Inter,ui-sans-serif,system-ui,sans-serif}*{box-sizing:border-box}body{margin:0;background:radial-gradient(circle at 80% -10%,#173126 0,transparent 32%),var(--bg);color:var(--text)}header,main{max-width:1320px;margin:auto;padding:24px}header{display:flex;justify-content:space-between;align-items:end;border-bottom:1px solid var(--line)}h1{margin:5px 0 0;font-size:clamp(30px,5vw,62px);letter-spacing:-.06em}h2{margin:5px 0 20px;font-size:24px}h3{margin:12px 0 5px}.eyebrow,label{color:var(--green);font:700 11px ui-monospace,monospace;letter-spacing:.14em}.status-dot{font:700 12px ui-monospace;padding:9px 12px;border:1px solid}.live{color:var(--green)}.danger{color:var(--red)}section{margin:28px 0}.status-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:12px}.status-grid article,.candidate,.mission,.split>div{background:linear-gradient(145deg,#10171b,#0b1013);border:1px solid var(--line);padding:18px}.status-grid strong{display:block;margin:12px 0}.status-grid span,small{display:block;color:var(--muted);font-size:12px}.stop{border-color:#6e2830!important}.section-head,.row,.money,.candidate>div,.actions{display:flex;align-items:center;justify-content:space-between;gap:10px}.lab{margin-top:26px}.cards{display:grid;grid-template-columns:repeat(2,1fr);gap:12px}.tag{font:700 10px ui-monospace;color:var(--green);border:1px solid #29543f;padding:4px 7px}.score{color:var(--amber);font:700 13px ui-monospace}.candidate p{color:#aebbb6;line-height:1.6}.candidate pre{overflow:auto;background:#070a0c;padding:12px;color:#9fb3ac}.actions{justify-content:flex-start;flex-wrap:wrap;margin-top:15px}.split{display:grid;grid-template-columns:1fr 1fr;gap:12px}.row{padding:12px 0;border-top:1px solid var(--line)}.tabs{color:var(--muted);font:12px ui-monospace;margin:-10px 0 18px}button,select{background:var(--green);border:0;padding:8px 11px;color:#07110b;font-weight:750}select{max-width:150px}button.secondary{background:#1a2429;color:var(--text)}.stop button{background:var(--red);color:#fff}.empty{padding:25px;border:1px dashed var(--line);color:var(--muted)}.money{padding:15px;background:var(--panel);border:1px solid var(--line);flex-wrap:wrap}form{display:flex;gap:5px;margin-top:10px}@media(max-width:850px){.status-grid,.cards,.split{grid-template-columns:1fr}header{align-items:start;gap:15px}.money{align-items:flex-start;flex-direction:column}}`;
