import { randomUUID } from 'node:crypto';
import type { DatabaseSync } from 'node:sqlite';
import { json,now,setting } from './db.js';
import { requireApprovedExternalAction,validateBaseUsageRights } from './policies.js';
import { ManualPaymentConfirmationProvider,type PaymentConfirmationProvider } from './integrations.js';
import type { ApprovalType,BusinessType,LeadStage } from './types.js';
import { BusinessEvents } from './events.js';

type Row=Record<string,unknown>;
const normalize=(value:string)=>value.trim().toLowerCase().replace(/^https?:\/\//,'').replace(/^www\./,'').replace(/\/$/,'');
const allowedTransitions:Record<LeadStage,LeadStage[]>={
  DISCOVERED:['QUALIFIED','LOST','NURTURE'],QUALIFIED:['PITCH_DRAFTED','LOST','NURTURE'],PITCH_DRAFTED:['AWAITING_APPROVAL'],AWAITING_APPROVAL:['PITCH_SENT','PITCH_DRAFTED','LOST'],PITCH_SENT:['FOLLOW_UP_DUE','REPLIED','LOST','NURTURE'],FOLLOW_UP_DUE:['PITCH_SENT','REPLIED','LOST','NURTURE'],REPLIED:['DISCOVERY','LOST','NURTURE'],DISCOVERY:['PROPOSAL_SENT','LOST','NURTURE'],PROPOSAL_SENT:['NEGOTIATION','WON','LOST'],NEGOTIATION:['WON','LOST','NURTURE'],WON:[],LOST:['NURTURE'],NURTURE:['QUALIFIED','LOST']
};

export class RevenueOps{
  private events:BusinessEvents;
  constructor(private db:DatabaseSync,private paymentProvider:PaymentConfirmationProvider=new ManualPaymentConfirmationProvider()){this.events=new BusinessEvents(db);}
  private audit(actorType:string,actorId:string,eventType:string,subjectType:string,subjectId:number|null,summary:string,detail:unknown={}):void{this.db.prepare('INSERT INTO audit_events(actor_type,actor_id,event_type,subject_type,subject_id,summary,detail_json,created_at) VALUES(?,?,?,?,?,?,?,?)').run(actorType,actorId,eventType,subjectType,subjectId,summary,json(detail),now());}
  createLead(input:{company:string;website?:string;productCategory:string;leadSource:string;fitReason:string;estimatedDealCents?:number;verifiedContact?:string;proposedConcept?:string;personalizationNotes?:string;isTest?:boolean}):number{
    if(!input.company.trim()||!input.productCategory.trim()||!input.fitReason.trim())throw new Error('Company, product category, and fit reason are required.');
    const company=normalize(input.company),website=normalize(input.website||'');
    const duplicate=this.db.prepare('SELECT id FROM leads WHERE normalized_company=? AND normalized_website=?').get(company,website) as {id:number}|undefined;
    if(duplicate)throw new Error(`Duplicate lead blocked; existing lead #${duplicate.id}.`);
    const result=this.db.prepare(`INSERT INTO leads(company,normalized_company,website,normalized_website,verified_contact,product_category,lead_source,fit_reason,proposed_concept,personalization_notes,estimated_deal_cents,stage,is_test,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`).run(input.company.trim(),company,input.website?.trim()||'',website,input.verifiedContact||null,input.productCategory.trim(),input.leadSource.trim(),input.fitReason.trim(),input.proposedConcept||null,input.personalizationNotes||null,input.estimatedDealCents||0,'DISCOVERED',input.isTest?1:0,now(),now());
    const id=Number(result.lastInsertRowid);this.audit('HUMAN','CHRIS','LEAD_CREATED','LEAD',id,`Lead ${input.company.trim()} created.`,{source:input.leadSource});return id;
  }
  moveLead(id:number,next:LeadStage,note=''):void{const lead=this.db.prepare('SELECT stage FROM leads WHERE id=?').get(id) as {stage:LeadStage}|undefined;if(!lead)throw new Error('Lead not found.');if(!allowedTransitions[lead.stage].includes(next))throw new Error(`Invalid lead transition ${lead.stage} → ${next}.`);this.db.prepare('UPDATE leads SET stage=?,updated_at=?,loss_reason=CASE WHEN ?=\'LOST\' THEN ? ELSE loss_reason END WHERE id=?').run(next,now(),next,note||null,id);this.audit('HUMAN','CHRIS','LEAD_STAGE_CHANGED','LEAD',id,`Lead moved ${lead.stage} → ${next}.`,{note});if(next==='QUALIFIED')this.events.record({eventType:'LEAD_QUALIFIED',subjectType:'LEAD',subjectId:id,idempotencyKey:`lead:${id}:qualified`});if(next==='WON')this.events.record({eventType:'PROPOSAL_ACCEPTED',subjectType:'LEAD',subjectId:id,idempotencyKey:`lead:${id}:won`});}
  draftPitch(leadId:number,body:string):{communicationId:number;approvalId:number}{if(!body.trim())throw new Error('Pitch body is required.');const lead=this.db.prepare('SELECT stage,company FROM leads WHERE id=?').get(leadId) as {stage:LeadStage;company:string}|undefined;if(!lead)throw new Error('Lead not found.');if(!['QUALIFIED','PITCH_DRAFTED'].includes(lead.stage))throw new Error('Lead must be QUALIFIED before drafting outreach.');const comm=Number(this.db.prepare(`INSERT INTO communications(lead_id,direction,communication_type,body,status,created_at) VALUES(?,'OUTBOUND','PITCH',?,'DRAFT',?)`).run(leadId,body.trim(),now()).lastInsertRowid);const approval=this.requestApproval('PROSPECT_OUTREACH','COMMUNICATION',comm,`Send initial pitch to ${lead.company}.`,'Personalized outreach is ready for human review.',{leadId,body:body.trim()},{risks:['External communication represents the business.']},'SCOUT');this.db.prepare('UPDATE communications SET approval_id=? WHERE id=?').run(approval,comm);if(lead.stage==='QUALIFIED')this.moveLead(leadId,'PITCH_DRAFTED');this.moveLead(leadId,'AWAITING_APPROVAL');return{communicationId:comm,approvalId:approval};}
  requestApproval(type:ApprovalType,subjectType:string,subjectId:number,actionSummary:string,recommendation:string,evidence:unknown,risks:unknown,agent:string,expiresAt?:string):number{const result=this.db.prepare(`INSERT INTO approvals(approval_type,subject_type,subject_id,action_summary,recommendation,evidence_json,risks_json,requesting_agent,requested_at,expires_at) VALUES(?,?,?,?,?,?,?,?,?,?)`).run(type,subjectType,subjectId,actionSummary,recommendation,json(evidence),json(risks),agent,now(),expiresAt||null);const id=Number(result.lastInsertRowid);this.audit('AGENT',agent,'APPROVAL_REQUESTED','APPROVAL',id,actionSummary,{type,subjectType,subjectId});return id;}
  decideApproval(id:number,status:'APPROVED'|'REJECTED'|'CHANGES_REQUESTED',note:string,actor='CHRIS'):void{const row=this.db.prepare("SELECT status FROM approvals WHERE id=?").get(id) as {status:string}|undefined;if(!row||row.status!=='PENDING')throw new Error('Approval is missing or no longer pending.');this.db.prepare('UPDATE approvals SET status=?,decided_at=?,decided_by=?,decision_note=? WHERE id=?').run(status,now(),actor,note||null,id);if(status==='APPROVED')this.db.prepare("UPDATE communications SET status='APPROVED' WHERE approval_id=? AND status='DRAFT'").run(id);this.audit('HUMAN',actor,'APPROVAL_DECIDED','APPROVAL',id,`Approval ${status.toLowerCase()}.`,{note});}
  recordPitchSent(communicationId:number,idempotencyKey:string):void{if(!idempotencyKey.trim())throw new Error('A send receipt identifier is required.');const comm=this.db.prepare(`SELECT c.*,a.status approval_status FROM communications c LEFT JOIN approvals a ON a.id=c.approval_id WHERE c.id=?`).get(communicationId) as Row|undefined;if(!comm)throw new Error('Communication not found.');const gate=requireApprovedExternalAction({approvalStatus:String(comm.approval_status||''),emergencyStop:setting(this.db,'emergency_stop',false),paused:setting(this.db,'outreach_paused',true)||setting(this.db,'global_automation_paused',true),idempotencyExists:Boolean(this.db.prepare('SELECT 1 FROM external_actions WHERE idempotency_key=?').get(idempotencyKey))});if(!gate.passed)throw new Error(gate.reasons.join(' '));this.db.prepare(`INSERT INTO external_actions(action_type,subject_type,subject_id,idempotency_key,approval_id,status,result_summary,created_at,updated_at) VALUES('OUTREACH','COMMUNICATION',?,?,?,?,?,?,?)`).run(communicationId,idempotencyKey,Number(comm.approval_id),'COMPLETED','Human confirmed the message was sent.',now(),now());this.db.prepare("UPDATE communications SET status='SENT',occurred_at=?,idempotency_key=? WHERE id=?").run(now(),idempotencyKey,communicationId);this.moveLead(Number(comm.lead_id),'PITCH_SENT');this.audit('HUMAN','CHRIS','OUTREACH_RECORDED','COMMUNICATION',communicationId,'Approved pitch recorded as sent.',{idempotencyKey});}
  createClientProject(leadId:number,packageId:number,title:string):number{const lead=this.db.prepare("SELECT * FROM leads WHERE id=? AND stage='WON'").get(leadId) as Row|undefined;if(!lead)throw new Error('Lead must be WON before client-project conversion.');const pkg=this.db.prepare('SELECT * FROM service_packages WHERE id=? AND active=1').get(packageId) as Row|undefined;if(!pkg)throw new Error('Active service package not found.');const clientName=String(lead.company),priceCents=Number(pkg.price_cents);const snapshot={code:pkg.code,name:pkg.name,priceCents,videoCount:pkg.video_count,revisionRounds:pkg.revision_rounds,organicUsage:true,paidAdUsage:false,rawFootage:false,perpetualUsage:false,exclusivity:false};const result=this.db.prepare(`INSERT INTO projects(business_type,lead_id,client_name,title,service_package_id,package_snapshot_json,goal_json,quoted_revenue_cents,status,is_test,created_at,updated_at) VALUES('CLIENT_UGC',?,?,?,?,?,'{"primary":"client approval, profitability, repeat order"}',?,'INTAKE',?,?,?)`).run(leadId,clientName,title,packageId,json(snapshot),priceCents,Number(lead.is_test)||0,now(),now());const id=Number(result.lastInsertRowid);this.db.prepare('INSERT INTO client_intakes(project_id,created_at,updated_at) VALUES(?,?,?)').run(id,now(),now());this.audit('HUMAN','CHRIS','CLIENT_PROJECT_CREATED','PROJECT',id,`Client project created for ${clientName}.`,{package:snapshot,isTest:Boolean(lead.is_test)});return id;}
  saveIntake(projectId:number,input:Record<string,string|number|boolean>):{complete:boolean;issues:string[]}{const required=['clientBrand','productInformation','targetCustomer','customerPainPoint','primaryBenefit','brandVoice','cta','usageType','requestedUsageTerm','revisionContact','finalApprover','aiProductionPolicy'];const issues=required.filter(key=>!String(input[key]??'').trim()).map(key=>`Missing ${key}.`);if(input.usageType==='PAID'&&!String(input.requestedUsageTerm||'').trim())issues.push('Paid usage requires a defined usage term.');const approved=String(input.approvedClaims||'').split('\n').map(x=>x.trim()).filter(Boolean),prohibited=String(input.prohibitedClaims||'').split('\n').map(x=>x.trim()).filter(Boolean);const conflicts=approved.filter(claim=>prohibited.includes(claim));if(conflicts.length)issues.push(`Claims appear in both approved and prohibited lists: ${conflicts.join(', ')}`);const text=(key:string,fallback:string|null=null):string|null=>{const value=input[key];return value===undefined||value===null||value===''?fallback:String(value);};this.db.prepare(`UPDATE client_intakes SET client_brand=?,product_information=?,target_customer=?,customer_pain_point=?,primary_benefit=?,approved_claims_json=?,prohibited_claims_json=?,brand_voice=?,cta=?,usage_type=?,requested_usage_term=?,revision_contact=?,final_approver=?,portfolio_permission=?,ai_production_policy=?,additional_instructions=?,contradictions_json=?,completion_status=?,updated_at=? WHERE project_id=?`).run(text('clientBrand'),text('productInformation'),text('targetCustomer'),text('customerPainPoint'),text('primaryBenefit'),json(approved),json(prohibited),text('brandVoice'),text('cta'),text('usageType'),text('requestedUsageTerm'),text('revisionContact'),text('finalApprover'),text('portfolioPermission','UNKNOWN'),text('aiProductionPolicy'),text('additionalInstructions'),json(issues),issues.length?'INCOMPLETE':'COMPLETE',now(),projectId);this.audit('HUMAN','CHRIS','INTAKE_UPDATED','PROJECT',projectId,issues.length?'Client intake remains incomplete.':'Client intake completed.',{issues});if(!issues.length)this.events.record({eventType:'INTAKE_COMPLETE',subjectType:'PROJECT',subjectId:projectId,idempotencyKey:`project:${projectId}:intake-complete`});return{complete:issues.length===0,issues};}
  saveIntakeDetails(projectId:number,input:Record<string,string|number|boolean>):void{const lines=(key:string)=>String(input[key]||'').split('\n').map(value=>value.trim()).filter(Boolean);const duration=Number(input.durationSeconds||0);this.db.prepare(`UPDATE client_intakes SET required_talking_points_json=?,required_visuals_json=?,preferred_examples_json=?,duration_seconds=?,aspect_ratio=?,raw_footage_requested=?,exclusivity_requested=?,deadline=?,shipping_status=?,updated_at=? WHERE project_id=?`).run(json(lines('requiredTalkingPoints')),json(lines('requiredVisuals')),json(lines('preferredExamples')),duration>0?duration:null,String(input.aspectRatio||'')||null,input.rawFootageRequested==='on'||input.rawFootageRequested===true?1:0,input.exclusivityRequested==='on'||input.exclusivityRequested===true?1:0,String(input.deadline||'')||null,String(input.shippingStatus||'')||null,now(),projectId);}
  addProjectAddon(projectId:number,addonId:number,quantity:number,priceCents:number,terms:unknown={}):void{
    if(quantity<1||priceCents<0)throw new Error('Add-on quantity and price must be valid.');
    const addon=this.db.prepare('SELECT active FROM package_addons WHERE id=?').get(addonId) as {active:number}|undefined;
    if(!addon?.active)throw new Error('Active add-on not found.');
    this.db.prepare('INSERT INTO project_addons(project_id,addon_id,quantity,price_cents,terms_json) VALUES(?,?,?,?,?) ON CONFLICT(project_id,addon_id) DO UPDATE SET quantity=excluded.quantity,price_cents=excluded.price_cents,terms_json=excluded.terms_json').run(projectId,addonId,quantity,priceCents,json(terms));
    this.audit('HUMAN','CHRIS','PROJECT_ADDON_QUOTED','PROJECT',projectId,'A separately priced usage or production add-on was recorded.',{addonId,quantity,priceCents});
  }
  createAgreement(projectId:number,input:{priceCents:number;depositCents:number;revisionRounds:number;turnaroundDays:number;paidAdUsage?:boolean;perpetualUsage?:boolean;rawFootageOwnership?:boolean;categoryExclusivity?:boolean;competitorExclusivity?:boolean;usageExpires?:string;portfolioPermission?:string}):number{
    const rights={paidAdUsage:Boolean(input.paidAdUsage),perpetualUsage:Boolean(input.perpetualUsage),rawFootageOwnership:Boolean(input.rawFootageOwnership),categoryExclusivity:Boolean(input.categoryExclusivity),competitorExclusivity:Boolean(input.competitorExclusivity)};
    const baseGate=validateBaseUsageRights(rights);
    const addonCodes=new Set((this.db.prepare('SELECT a.code FROM project_addons pa JOIN package_addons a ON a.id=pa.addon_id WHERE pa.project_id=?').all(projectId) as {code:string}[]).map(row=>row.code));
    const required:Record<keyof typeof rights,string>={paidAdUsage:'PAID_AD_USAGE',perpetualUsage:'PERPETUAL_USAGE',rawFootageOwnership:'RAW_FOOTAGE',categoryExclusivity:'CATEGORY_EXCLUSIVITY',competitorExclusivity:'COMPETITOR_EXCLUSIVITY'};
    const unquoted=(Object.keys(rights) as (keyof typeof rights)[]).filter(key=>rights[key]&&!addonCodes.has(required[key]));
    if(!baseGate.passed&&unquoted.length)throw new Error(`Add-on rights require explicit quoted project add-ons: ${unquoted.map(key=>required[key]).join(', ')}.`);
    const existing=this.db.prepare('SELECT id FROM agreements WHERE project_id=?').get(projectId) as {id:number}|undefined;
    if(existing){this.db.prepare(`UPDATE agreements SET price_cents=?,deposit_cents=?,remaining_cents=?,revision_rounds=?,turnaround_days=?,organic_usage=1,paid_ad_usage=?,usage_expires=?,perpetual_usage=?,raw_footage_ownership=?,category_exclusivity=?,competitor_exclusivity=?,portfolio_permission=?,signature_status='DRAFT',client_approved_at=NULL,creator_approved_at=NULL,updated_at=? WHERE id=?`).run(input.priceCents,input.depositCents,Math.max(0,input.priceCents-input.depositCents),input.revisionRounds,input.turnaroundDays,rights.paidAdUsage?1:0,input.usageExpires||null,rights.perpetualUsage?1:0,rights.rawFootageOwnership?1:0,rights.categoryExclusivity?1:0,rights.competitorExclusivity?1:0,input.portfolioPermission||'UNKNOWN',now(),existing.id);this.audit('HUMAN','CHRIS','AGREEMENT_UPDATED','PROJECT',projectId,'Agreement and usage rights updated.',{agreementId:existing.id,rights});return existing.id;}
    const result=this.db.prepare(`INSERT INTO agreements(project_id,deliverables_json,price_cents,deposit_cents,remaining_cents,revision_rounds,turnaround_days,organic_usage,paid_ad_usage,usage_expires,perpetual_usage,raw_footage_ownership,category_exclusivity,competitor_exclusivity,portfolio_permission,signature_status,created_at,updated_at) VALUES(?,'[]',?,?,?,?,?,1,?,?,?, ?,?,?,?,'DRAFT',?,?)`).run(projectId,input.priceCents,input.depositCents,Math.max(0,input.priceCents-input.depositCents),input.revisionRounds,input.turnaroundDays,rights.paidAdUsage?1:0,input.usageExpires||null,rights.perpetualUsage?1:0,rights.rawFootageOwnership?1:0,rights.categoryExclusivity?1:0,rights.competitorExclusivity?1:0,input.portfolioPermission||'UNKNOWN',now(),now());
    const id=Number(result.lastInsertRowid);this.audit('HUMAN','CHRIS','AGREEMENT_DRAFTED','PROJECT',projectId,'Agreement and usage rights recorded.',{agreementId:id,rights,legalNotice:'Template fields are operational records, not legal advice.'});return id;
  }
  acceptAgreement(agreementId:number):void{const agreement=this.db.prepare('SELECT project_id FROM agreements WHERE id=?').get(agreementId) as {project_id:number}|undefined;if(!agreement)throw new Error('Agreement not found.');this.db.prepare("UPDATE agreements SET signature_status='ACCEPTED',client_approved_at=?,creator_approved_at=?,updated_at=? WHERE id=?").run(now(),now(),now(),agreementId);this.db.prepare("UPDATE projects SET status='ACTIVE',updated_at=? WHERE id=?").run(now(),agreement.project_id);this.audit('HUMAN','CHRIS','AGREEMENT_ACCEPTED','PROJECT',agreement.project_id,'Client and creator approval were recorded.',{agreementId});}
  recordFinancialEntry(projectId:number,businessType:BusinessType,entryType:'REVENUE'|'EXPENSE'|'REFUND'|'COMMISSION'|'INVOICE',amountCents:number,status:'ESTIMATED'|'PENDING'|'CONFIRMED',description:string,sourceType?:string,sourceId?:number):number{const project=this.db.prepare('SELECT business_type FROM projects WHERE id=?').get(projectId) as {business_type:BusinessType}|undefined;if(!project)throw new Error('Project not found.');if(project.business_type!==businessType)throw new Error(`Financial separation violation: project is ${project.business_type}, not ${businessType}.`);return Number(this.db.prepare('INSERT INTO financial_entries(project_id,business_type,entry_type,amount_cents,status,occurred_at,description,source_type,source_id,created_at) VALUES(?,?,?,?,?,?,?,?,?,?)').run(projectId,businessType,entryType,amountCents,status,now(),description,sourceType||null,sourceId||null,now()).lastInsertRowid);}
  createInvoice(projectId:number,amountCents:number,kind:'DEPOSIT'|'BALANCE'|'FULL',dueAt?:string):number{const project=this.db.prepare('SELECT business_type FROM projects WHERE id=?').get(projectId) as {business_type:BusinessType}|undefined;if(project?.business_type!=='CLIENT_UGC')throw new Error('Client invoices may only be attached to CLIENT_UGC projects.');if(!Number.isInteger(amountCents)||amountCents<=0)throw new Error('Invoice amount must be positive.');const number=`UGC-${projectId}-${Date.now()}-${randomUUID().slice(0,6)}`;const id=Number(this.db.prepare(`INSERT INTO invoices(project_id,invoice_number,amount_cents,kind,status,due_at,created_at,updated_at) VALUES(?,?,?,?,'DRAFT',?,?,?)`).run(projectId,number,amountCents,kind,dueAt||null,now(),now()).lastInsertRowid);this.recordFinancialEntry(projectId,'CLIENT_UGC','INVOICE',amountCents,'PENDING','Client invoice','INVOICE',id);this.audit('HUMAN','CHRIS','INVOICE_CREATED','PROJECT',projectId,'Manual client invoice record created.',{invoiceId:id,amountCents,kind,dueAt});return id;}
  confirmPayment(invoiceId:number,amountCents:number,idempotencyKey:string):number{const paymentGate=this.paymentProvider.validate({amountCents,idempotencyKey});if(!paymentGate.valid)throw new Error(paymentGate.reasons.join(' '));if(this.db.prepare('SELECT 1 FROM payments WHERE idempotency_key=?').get(idempotencyKey))throw new Error('Duplicate payment confirmation blocked.');const invoice=this.db.prepare(`SELECT i.*,p.business_type FROM invoices i JOIN projects p ON p.id=i.project_id WHERE i.id=?`).get(invoiceId) as Row|undefined;if(!invoice)throw new Error('Invoice not found.');if(invoice.business_type!=='CLIENT_UGC')throw new Error('Payment/project business type mismatch.');const projectId=Number(invoice.project_id);const prior=(this.db.prepare("SELECT COALESCE(SUM(amount_cents),0) total FROM payments WHERE invoice_id=? AND status='CONFIRMED'").get(invoiceId) as {total:number}).total;if(prior+amountCents>Number(invoice.amount_cents))throw new Error('Payment confirmation exceeds the invoice balance.');const id=Number(this.db.prepare(`INSERT INTO payments(invoice_id,amount_cents,status,provider,idempotency_key,confirmed_at,recorded_by,created_at) VALUES(?,?,'CONFIRMED','MANUAL',?,?, 'CHRIS',?)`).run(invoiceId,amountCents,idempotencyKey,now(),now()).lastInsertRowid);const paid=prior+amountCents;this.db.prepare('UPDATE invoices SET status=?,updated_at=? WHERE id=?').run(paid>=Number(invoice.amount_cents)?'PAID':'PARTIALLY_PAID',now(),invoiceId);this.recordFinancialEntry(projectId,'CLIENT_UGC','REVENUE',amountCents,'CONFIRMED','Client payment','PAYMENT',id);this.db.prepare('UPDATE projects SET actual_revenue_cents=actual_revenue_cents+?,updated_at=? WHERE id=?').run(amountCents,now(),projectId);this.audit('HUMAN','CHRIS','PAYMENT_CONFIRMED','INVOICE',invoiceId,'Manual payment confirmation recorded.',{amountCents,paymentId:id});this.events.record({eventType:'PAYMENT_RECEIVED',subjectType:'PROJECT',subjectId:projectId,idempotencyKey:`payment:${id}:received`,payload:{invoiceId,amountCents}});return id;}
  createProductionItem(projectId:number,title:string,format:string):number{if(setting(this.db,'emergency_stop',false)||setting(this.db,'production_paused',true))throw new Error('Production is paused by Hermes controls.');const gate=this.db.prepare(`SELECT ci.completion_status,a.signature_status,a.deposit_cents,COALESCE((SELECT SUM(pay.amount_cents) FROM payments pay JOIN invoices i ON i.id=pay.invoice_id WHERE i.project_id=? AND pay.status='CONFIRMED'),0) paid_cents FROM client_intakes ci LEFT JOIN agreements a ON a.project_id=ci.project_id WHERE ci.project_id=?`).get(projectId,projectId) as {completion_status:string;signature_status:string|null;deposit_cents:number|null;paid_cents:number}|undefined;if(!gate||gate.completion_status!=='COMPLETE')throw new Error('Complete client intake before production starts.');if(gate.signature_status!=='ACCEPTED')throw new Error('Accepted agreement required before production starts.');if(Number(gate.paid_cents)<Number(gate.deposit_cents||0))throw new Error('Required deposit must be confirmed before production starts.');const id=Number(this.db.prepare(`INSERT INTO production_items(project_id,title,format,stage,created_at,updated_at) VALUES(?,?,?,'BRIEF',?,?)`).run(projectId,title,format,now(),now()).lastInsertRowid);this.audit('HUMAN','CHRIS','PRODUCTION_STARTED','PRODUCTION_ITEM',id,'Production item created after intake, agreement, deposit, and pause gates passed.',{projectId});return id;}
  moveProductionItem(itemId:number,stage:string,blockedReason=''):void{const allowed=['IDEA','RESEARCH','BRIEF','SCRIPT','ASSETS_NEEDED','READY_TO_GENERATE','GENERATING','INTERNAL_QA','CLIENT_REVIEW','REVISION','APPROVED','SCHEDULED','PUBLISHED','DELIVERED','ARCHIVED','BLOCKED'];if(!allowed.includes(stage))throw new Error('Invalid production stage.');if(!['BLOCKED','ARCHIVED'].includes(stage)&&(setting(this.db,'emergency_stop',false)||setting(this.db,'production_paused',true)))throw new Error('Production is paused by Hermes controls.');this.db.prepare('UPDATE production_items SET stage=?,blocked_reason=?,updated_at=? WHERE id=?').run(stage,stage==='BLOCKED'?blockedReason||'Manual block':null,now(),itemId);this.audit('HUMAN','CHRIS','PRODUCTION_STAGE_CHANGED','PRODUCTION_ITEM',itemId,`Production item moved to ${stage}.`,{blockedReason});}
  recordProjectCheck(projectId:number,itemId:number|undefined,checkType:'CLAIM'|'DISCLOSURE'|'HOOK'|'CTA'|'END_CARD'|'CREATIVE_VARIETY'|'PLATFORM_POLICY'|'QUALITY',passed:boolean,reasons:string[]=[],evidence:unknown={},versionId?:number):number{const resolvedVersionId=versionId||(itemId?(this.db.prepare('SELECT id FROM deliverable_versions WHERE production_item_id=? ORDER BY version_number DESC LIMIT 1').get(itemId) as {id:number}|undefined)?.id:undefined);if(!resolvedVersionId)throw new Error('Attach a deliverable version before recording QA.');const version=this.db.prepare('SELECT 1 FROM deliverable_versions v JOIN production_items pi ON pi.id=v.production_item_id WHERE v.id=? AND pi.id=? AND pi.project_id=?').get(resolvedVersionId,itemId||0,projectId);if(!version)throw new Error('QA version does not belong to this project item.');const id=Number(this.db.prepare('INSERT INTO project_checks(project_id,production_item_id,version_id,check_type,passed,reasons_json,evidence_json,checked_by,created_at) VALUES(?,?,?,?,?,?,?,?,?)').run(projectId,itemId||null,resolvedVersionId,checkType,passed?1:0,json(reasons),json(evidence),'VANTAGE',now()).lastInsertRowid);this.audit('AGENT','VANTAGE','PROJECT_CHECK_RECORDED','PROJECT',projectId,`${checkType} check ${passed?'passed':'failed'}.`,{checkId:id,versionId:resolvedVersionId,reasons});if(!passed)this.events.record({eventType:'QA_FAILED',subjectType:itemId?'PRODUCTION_ITEM':'PROJECT',subjectId:itemId||projectId,idempotencyKey:`check:${id}:failed`,payload:{projectId,checkType,reasons}});return id;}
  requestRevision(itemId:number,versionId:number,requestText:string):number{if(!requestText.trim())throw new Error('Revision request cannot be empty.');const scope=this.db.prepare(`SELECT a.revision_rounds,(SELECT COUNT(*) FROM revisions r WHERE r.production_item_id=?) prior_count,pi.project_id FROM production_items pi JOIN agreements a ON a.project_id=pi.project_id WHERE pi.id=?`).get(itemId,itemId) as {revision_rounds:number;prior_count:number;project_id:number}|undefined;if(!scope)throw new Error('Signed project agreement required before revisions.');const warning=Number(scope.prior_count)+1>Number(scope.revision_rounds);const id=Number(this.db.prepare("INSERT INTO revisions(production_item_id,version_id,requested_by,request_text,status,scope_warning,created_at) VALUES(?,?,'CLIENT',?,'REQUESTED',?,?)").run(itemId,versionId,requestText.trim(),warning?1:0,now()).lastInsertRowid);this.moveProductionItem(itemId,'REVISION');this.events.record({eventType:'REVISION_REQUESTED',subjectType:'PRODUCTION_ITEM',subjectId:itemId,idempotencyKey:`revision:${id}:requested`,payload:{versionId,scopeWarning:warning}});if(warning)this.events.record({eventType:'REVISION_SCOPE_WARNING',subjectType:'PROJECT',subjectId:scope.project_id,idempotencyKey:`revision:${id}:scope-warning`,payload:{revisionId:id,allowedRounds:scope.revision_rounds}});this.audit('SYSTEM','VANTAGE',warning?'REVISION_SCOPE_WARNING':'REVISION_RECORDED','REVISION',id,warning?'Revision exceeds the signed allowance; scope approval is required.':'Revision is within the signed allowance.',{allowedRounds:scope.revision_rounds});return id;}
  archiveProject(projectId:number):void{const project=this.db.prepare('SELECT status,is_test FROM projects WHERE id=?').get(projectId) as {status:string;is_test:number}|undefined;if(!project)throw new Error('Project not found.');if(!project.is_test&&project.status!=='DELIVERED')throw new Error('Only delivered or test projects may be archived.');this.db.prepare("UPDATE projects SET status='ARCHIVED',updated_at=? WHERE id=?").run(now(),projectId);this.db.prepare("UPDATE production_items SET stage='ARCHIVED',updated_at=? WHERE project_id=? AND stage!='ARCHIVED'").run(now(),projectId);this.audit('HUMAN','CHRIS','PROJECT_ARCHIVED','PROJECT',projectId,'Project archived without deleting its audit history.',{isTest:Boolean(project.is_test)});}
  completeRevision(revisionId:number):void{this.db.prepare("UPDATE revisions SET status='COMPLETED',completed_at=? WHERE id=?").run(now(),revisionId);}
  recordProjectExpense(projectId:number,amountCents:number,description:string):number{const project=this.db.prepare('SELECT business_type FROM projects WHERE id=?').get(projectId) as {business_type:BusinessType}|undefined;if(!project)throw new Error('Project not found.');const id=this.recordFinancialEntry(projectId,project.business_type,'EXPENSE',amountCents,'CONFIRMED',description);this.db.prepare('UPDATE projects SET expense_cents=expense_cents+?,updated_at=? WHERE id=?').run(amountCents,now(),projectId);return id;}
  addProductionMinutes(projectId:number,minutes:number):void{if(!Number.isFinite(minutes)||minutes<=0)throw new Error('Production minutes must be positive.');this.db.prepare('UPDATE projects SET production_minutes=production_minutes+?,updated_at=? WHERE id=?').run(Math.round(minutes),now(),projectId);}
  createFollowup(projectId:number,type:'TESTIMONIAL'|'REPEAT_ORDER',message:string):number{if(!message.trim())throw new Error('Follow-up message is required.');const id=Number(this.db.prepare("INSERT INTO client_followups(project_id,followup_type,status,message,created_at,updated_at) VALUES(?,?,'DRAFT',?,?,?)").run(projectId,type,message.trim(),now(),now()).lastInsertRowid);this.db.prepare(`UPDATE projects SET ${type==='TESTIMONIAL'?'testimonial_status':'repeat_order_status'}=?,updated_at=? WHERE id=?`).run(type==='TESTIMONIAL'?'REQUESTED':'PROMPTED',now(),projectId);this.audit('HUMAN','CHRIS','CLIENT_FOLLOWUP_PREPARED','PROJECT',projectId,`${type} follow-up prepared for manual sending.`,{followupId:id});return id;}
  recordDownload(deliveryId:number):void{this.db.prepare("INSERT INTO download_events(delivery_id,downloaded_at,recorded_by) VALUES(?,?,'CHRIS')").run(deliveryId,now());this.db.prepare('UPDATE deliveries SET download_count=download_count+1,last_download_at=? WHERE id=?').run(now(),deliveryId);}
  addPortfolioItem(projectId:number|undefined,input:{title:string;productBrand?:string;category:string;format:'PRODUCT_DEMONSTRATION'|'PROBLEM_SOLUTION'|'TESTIMONIAL'|'UNBOXING'|'SOFTWARE_WEBSITE_DEMO';description:string;permissionStatus:'UNKNOWN'|'REQUESTED'|'GRANTED'|'DENIED'|'SELF_INITIATED';visibility:'PUBLIC'|'PRIVATE';featured?:boolean;videoUri?:string;thumbnailUri?:string;skills?:string[]}):number{if(input.visibility==='PUBLIC'&&!['GRANTED','SELF_INITIATED'].includes(input.permissionStatus))throw new Error('Public portfolio visibility requires granted permission or a self-initiated label.');return Number(this.db.prepare('INSERT INTO portfolio_items(project_id,title,product_brand,category,ugc_format,video_uri,thumbnail_uri,description,skills_json,permission_status,featured,visibility,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?)').run(projectId||null,input.title,input.productBrand||null,input.category,input.format,input.videoUri||null,input.thumbnailUri||null,input.description,json(input.skills||[]),input.permissionStatus,input.featured?1:0,input.visibility,now(),now()).lastInsertRowid);}
  addVersion(itemId:number,fileUri:string,watermarked:boolean,status='DRAFT',sha256?:string):number{if(!fileUri.trim())throw new Error('File reference is required.');const next=(this.db.prepare('SELECT COALESCE(MAX(version_number),0)+1 next FROM deliverable_versions WHERE production_item_id=?').get(itemId) as {next:number}).next;return Number(this.db.prepare('INSERT INTO deliverable_versions(production_item_id,version_number,file_uri,watermarked,status,sha256,created_at) VALUES(?,?,?,?,?,?,?)').run(itemId,next,fileUri,watermarked?1:0,status,sha256||null,now()).lastInsertRowid);}
  deliver(projectId:number,versionId:number,type:'WATERMARKED_DRAFT'|'FINAL_UNWATERMARKED',idempotencyKey:string=randomUUID(),paymentOverrideApprovalId?:number):number{if(!idempotencyKey.trim())throw new Error('A delivery receipt identifier is required.');if(setting(this.db,'emergency_stop',false)||setting(this.db,'delivery_paused',false)||setting(this.db,'global_automation_paused',true))throw new Error('Delivery is paused by Hermes controls.');if(this.db.prepare('SELECT 1 FROM deliveries WHERE idempotency_key=?').get(idempotencyKey))throw new Error('Duplicate delivery blocked.');const version=this.db.prepare(`SELECT v.*,p.stage FROM deliverable_versions v JOIN production_items p ON p.id=v.production_item_id WHERE v.id=? AND p.project_id=?`).get(versionId,projectId) as Row|undefined;if(!version)throw new Error('Deliverable version not found for project.');if(type==='WATERMARKED_DRAFT'&&!Boolean(version.watermarked))throw new Error('Draft delivery must be watermarked.');let approvalId:number|undefined;if(type==='FINAL_UNWATERMARKED'){
      if(Boolean(version.watermarked))throw new Error('Final delivery must use an unwatermarked version.');const agreement=this.db.prepare("SELECT signature_status FROM agreements WHERE project_id=?").get(projectId) as {signature_status:string}|undefined;if(agreement?.signature_status!=='ACCEPTED')throw new Error('Final delivery requires an accepted agreement.');const approval=this.db.prepare("SELECT id FROM approvals WHERE subject_type='PROJECT' AND subject_id=? AND approval_type='FINAL_DELIVERY' AND status='APPROVED' ORDER BY id DESC LIMIT 1").get(projectId) as {id:number}|undefined;approvalId=approval?.id;const invoiceState=this.db.prepare("SELECT COUNT(*) count,SUM(CASE WHEN status NOT IN ('PAID','VOID','REFUNDED') THEN 1 ELSE 0 END) unpaid FROM invoices WHERE project_id=?").get(projectId) as {count:number;unpaid:number};const override=paymentOverrideApprovalId?this.db.prepare("SELECT 1 FROM approvals WHERE id=? AND subject_type='PROJECT' AND subject_id=? AND approval_type='PAYMENT_OVERRIDE' AND status='APPROVED'").get(paymentOverrideApprovalId,projectId):undefined;if(!approvalId)throw new Error('Final delivery requires explicit human approval.');if((invoiceState.count===0||invoiceState.unpaid>0)&&!override)throw new Error('Unwatermarked final delivery blocked until payment requirements are recorded and satisfied.');
    }const required=['CLAIM','DISCLOSURE','QUALITY'];const latest=this.db.prepare("SELECT check_type,passed FROM project_checks WHERE project_id=? AND version_id=? AND id IN (SELECT MAX(id) FROM project_checks WHERE project_id=? AND version_id=? GROUP BY check_type)").all(projectId,versionId,projectId,versionId) as {check_type:string;passed:number}[];const passed=new Set(latest.filter(row=>row.passed).map(row=>row.check_type));const missing=required.filter(check=>!passed.has(check));if(missing.length)throw new Error(`${type==='FINAL_UNWATERMARKED'?'Final':'Draft'} delivery requires version-specific passing checks: ${missing.join(', ')}.`);const receiptCode=`UGC-RECEIPT-${projectId}-${randomUUID().slice(0,8).toUpperCase()}`;const id=Number(this.db.prepare(`INSERT INTO deliveries(project_id,version_id,delivery_type,status,delivered_at,delivered_by,approval_id,payment_override_approval_id,idempotency_key,receipt_code,created_at) VALUES(?,?,?,'DELIVERED',?,'CHRIS',?,?,?,?,?)`).run(projectId,versionId,type,now(),approvalId||null,paymentOverrideApprovalId||null,idempotencyKey,receiptCode,now()).lastInsertRowid);this.db.prepare("UPDATE deliverable_versions SET status='DELIVERED' WHERE id=?").run(versionId);if(type==='FINAL_UNWATERMARKED'){this.db.prepare("UPDATE projects SET status='DELIVERED',updated_at=? WHERE id=?").run(now(),projectId);this.events.record({eventType:'FINAL_DELIVERED',subjectType:'PROJECT',subjectId:projectId,idempotencyKey:`delivery:${id}:final`,payload:{versionId,receiptCode}});}this.audit('HUMAN','CHRIS','DELIVERY_RECORDED','PROJECT',projectId,`${type} delivery recorded.`,{versionId,deliveryId:id,receiptCode});return id;}
}
